services:
  souzai-kako-app:
    build:
      context: .
    container_name: ujian-app
    restart: unless-stopped
    environment:
      PORT: "9091"
      HOST: "0.0.0.0"
    ports:
      - "9091:9091"

  cloudflared:
    profiles: ["public"]
    image: cloudflare/cloudflared:latest
    container_name: souzai-kako-cloudflared
    restart: unless-stopped
    depends_on:
      - souzai-kako-app
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN:-}
